-- Revert MyMusicalWorld:alter_table_liaison from pg

BEGIN;

ALTER TABLE USER_LIKES_ALBUM 
DROP COLUMN api_id,
ADD COLUMN album_id INT NOT NULL REFERENCES ALBUM (id);

ALTER TABLE USER_LIKES_ARTIST
DROP COLUMN api_id,
ADD COLUMN artist_id INT NOT NULL REFERENCES ARTIST (id);

ALTER TABLE USER_LIKES_TRACK 
DROP COLUMN api_id,
ADD COLUMN track_id INT NOT NULL REFERENCES TRACK (id);


COMMIT;
