-- Deploy MyMusicalWorld:alter_table_liaison to pg

BEGIN;

TRUNCATE TABLE USER_LIKES_ALBUM CASCADE;
ALTER TABLE USER_LIKES_ALBUM 
DROP COLUMN album_id CASCADE,
ADD api_id INT NOT NULL REFERENCES ALBUM(api_id);

TRUNCATE TABLE USER_LIKES_ARTIST CASCADE;
ALTER TABLE USER_LIKES_ARTIST 
DROP COLUMN artist_id CASCADE,
ADD api_id INT NOT NULL REFERENCES ARTIST(api_id);

TRUNCATE TABLE USER_LIKES_TRACK CASCADE;
ALTER TABLE USER_LIKES_TRACK 
DROP COLUMN track_id CASCADE,
ADD api_id INT NOT NULL REFERENCES TRACK(api_id);

COMMIT;
