-- Verify MyMusicalWorld:init on pg

BEGIN;

SELECT * FROM USER_LIKES_ALBUM WHERE false;
SELECT * FROM USER_LIKES_TRACK WHERE false;
SELECT * FROM USER_LIKES_ARTIST WHERE false;
SELECT * FROM TRACK WHERE false;
SELECT * FROM ARTIST WHERE false;
SELECT * FROM ALBUM WHERE false;
SELECT * FROM USER WHERE false;

ROLLBACK;
