CREATE DATABASE UTILISATEURS;
\c UTILISATEURS;

CREATE TABLE AIME (
  api_id VARCHAR(42),
  mail VARCHAR(42),
  PRIMARY KEY (api_id, mail)
);

CREATE TABLE UTILISATEUR (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  mail TEXT NOT NULL UNIQUE,
  nom TEXT NOT NULL,
  prénom TEXT NOT NULL,
  pseudo  TEXT NOT NULL UNIQUE,
  mot_de_passe TEXT NOT NULL UNIQUE
);

CREATE TABLE APPRECIE (
  api_id VARCHAR(42),
  mail VARCHAR(42),
  PRIMARY KEY (api_id, mail)
);

CREATE TABLE ALBUM (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  genre TEXT,
  artiste TEXT NOT NULL,
  année INT,
  url_image TEXT,
  api_id INT NOT NULL
);

CREATE TABLE LIKE (
  api_id VARCHAR(42),
  mail VARCHAR(42),
  PRIMARY KEY (api_id, mail)
);

CREATE TABLE ARTISTE (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  genre TEXT,
  url_image TEXT,
  api_id INT NOT NULL
);

CREATE TABLE TITRE (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  genre VARCHAR(42),
  artiste TEXT NOT NULL,
  année VARCHAR(42),
  album VARCHAR(42),
  url_image VARCHAR(42),
  api_id VARCHAR(42),
  url_extrait VARCHAR(42),
  PRIMARY KEY (api_id)
);

ALTER TABLE AIME ADD FOREIGN KEY (mail) REFERENCES UTILISATEUR (mail);
ALTER TABLE AIME ADD FOREIGN KEY (api_id) REFERENCES ALBUM (api_id);
ALTER TABLE APPRECIE ADD FOREIGN KEY (mail) REFERENCES UTILISATEUR (mail);
ALTER TABLE APPRECIE ADD FOREIGN KEY (api_id) REFERENCES ARTISTE (api_id);
ALTER TABLE LIKE ADD FOREIGN KEY (mail) REFERENCES UTILISATEUR (mail);
ALTER TABLE LIKE ADD FOREIGN KEY (api_id) REFERENCES TITRE (api_id);